import json

def apply_translations():
    filepath = 'impro_games_cleaned.json'

    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # This dictionary holds the improved Polish descriptions.
    # I have generated these using better translation methods.
    # I will also correct the English descriptions where they were mistakenly in Polish.
    translations = {
        33: {
            "opis": "Każdy gracz (lub gospodarz) prosi o losowe zwierzęta i kontynuuje scenę, wykorzystując cechy danego zwierzęcia."
        },
        34: {
            "opis_ang": "Ask the audience for animals. Players play a scene in which the characters are based on those animals. Notes: Players don't 'become' the animals, they only take on their characteristics. Characteristics can be physical, vocal, or status-based. For example, a 'chicken' might inspire a player to a cowardly character, moving nervously. Also known as Totems - you can play this as an exercise: write the names of totems on slips of paper. Give each player a totem before they play a scene. You can extend the name of the animal; make it more specific. Play with things like Bald Eagle instead of Eagle; or Silver Moon, Sitting Bull, etc.",
            "opis": "Zapytajcie publiczność o zwierzęta. Gracze odgrywają scenkę, w której postacie są oparte na cechach tych zwierząt. Uwagi: Gracze nie „stają się” zwierzętami, a jedynie przejmują ich cechy. Cechy mogą być fizyczne, głosowe lub oparte na statusie. Na przykład, postać inspirowana „kurczakiem” może być tchórzliwa i poruszać się nerwowo. Gra znana również jako Totemy – można ją rozegrać jako ćwiczenie: napiszcie nazwy totemów na kartkach papieru i dajcie każdemu graczowi jedną, zanim odegrają scenę. Możecie też uszczegółowić nazwę zwierzęcia, np. Łysy Orzeł zamiast Orła, lub Srebrzysty Wilk, Siedzący Byk itp."
        },
        35: {
            "opis_ang": "Make sure you have an even number of players. Give everyone an animal, but make sure there are 2 of each, and that no one knows which player is which animal. Then give some activities the animals do. Try: Eating. Eating when you're really hungry. Drinking. Drinking when you're really thirsty. Making love. Grooming. Fighting. Sleeping. Finally, ask players to find the other animal of their species. Ask the others if they found out who is what animal. Variations: Have 2 players be humans.",
            "opis": "Upewnijcie się, że macie parzystą liczbę graczy. Każdemu przydzielcie zwierzę, ale tak, aby były po dwa takie same, a nikt nie wie, kto jest jakim zwierzęciem. Następnie podajcie kilka czynności, które wykonują zwierzęta. Spróbujcie: Jedzenie. Jedzenie w wielkim głodzie. Picie. Picie w wielkim pragnieniu. Kochanie się. Pielęgnacja. Walka. Spanie. Na koniec poproście graczy, aby odnaleźli drugie zwierzę ze swojego gatunku. Zapytajcie pozostałych, czy odgadli, kto jest jakim zwierzęciem. Wariacje: Niech dwóch graczy będzie ludźmi."
        },
        36: {
            "opis": "Gospodarz zamraża scenę i podaje nowego autora z listy."
        },
        37: {
            "opis": "Zbierzcie sugestie dotyczące imienia, postawy/cechy i zawodu. Następnie odegrajcie tę postać w krótkiej, dwuosobowej scence (drugi gracz powinien stworzyć postać uzupełniającą). Można grać w kręgu."
        },
        38: {
            "opis": "Zdobądźcie inicjały od kogoś z publiczności. Jedna drużyna wykrzykuje frazę postaci zaczynającą się od tych inicjałów (np. „Zirytowani Naukowcy” lub „Obfite Smerfy”), druga drużyna wsiada do „samochodu” i staje się tymi postaciami. Druga drużyna próbuje ich oznaczyć, ale przed tym powinna wykrzyczeć frazę dla przeciwnej drużyny."
        },
        39: {
            "opis": "Zbierzcie sugestie dotyczące imienia, cechy charakteru i zawodu. Jeden gracz staje się tą postacią, a pozostali zmieniają się, odkrywając różne strony tej postaci: różne środowiska, różne powody takiego zachowania (przynoście jasne, konkretne oferty)."
        },
        40: {
            "opis": "Dwóch graczy improwizuje scenę, dokonując wyraźnych, mocnych wyborów fizycznych i wokalnych. Scena jest odgrywana do momentu, gdy postacie zostaną dobrze zarysowane. Następnie role się odwracają i każdy z graczy gra postać drugiego, w tej samej scenie i w tym samym miejscu. Ćwiczenie to trenuje słuchanie i obserwację fizyczną, a także jest świetnym sposobem na oderwanie się graczy od ich stałych postaci."
        },
        41: {
            "opis_ang": "Great exercise for character development. Players walk around the room as themselves. Ask players to find some inspiration, and then use that to change their walk. Anything can be used as inspiration: use an emotion (happy!), a profession (farmer!), a stereotype (Irishman!), an animal (Snake!) or even an object (grandfather clock!). Then transform the way you walk into a character. Explore how the character walks, and - by association - find out as much as you can about this character. Variations: If you use the way of moving as inspiration, you end up with something like Fast Food Laban.",
            "opis": "Świetne ćwiczenie na rozwój postaci. Gracze spacerują po pokoju jako oni sami. Poproście ich, aby znaleźli jakąś inspirację, a następnie wykorzystali ją do zmiany swojego chodu. Inspiracją może być wszystko: emocja (szczęśliwy!), zawód (rolnik!), stereotyp (Irlandczyk!), zwierzę (wąż!) lub nawet przedmiot (zegar dziadka!). Następnie przekształćcie sposób chodzenia w postać. Zbadajcie, jak dana postać chodzi i – przez skojarzenie – dowiedzcie się o niej jak najwięcej. Wariacje: Jeśli jako inspirację wykorzystacie sposób poruszania się, możecie skończyć z czymś w rodzaju Fast Food Laban."
        },
        42: {
            "opis": "1. Głowa (chód zależny od wieku/płci/zawodu/znanej osoby) 2. Serce (chód emocjonalny) 3. Ciało (podpowiedzi fizyczne: wolno/szybko, ciężko/lekko, prowadzenie ruchem przez różne części ciała)."
        },
        43: {
            "opis_ang": "Ask players to think of someone they know. Then ask them to play out how that person would come home from work. Players need to pay attention to: The environment: what does this person's house look like? Is it neat and tidy, or is it a mess? Big house or small apartment? What does the person do? Does the character change clothes, or take a shower, or have a beer first? Does she eat something? If so, what? A microwave dinner, take-out, pizza-delivery or cornflakes? What mood is the character in? How was work today? Variations: You can invent other situations in which characters enter a location.",
            "opis": "Poproście graczy, aby pomyśleli o kimś, kogo znają. Następnie niech odegrają, jak ta osoba wraca do domu z pracy. Gracze muszą zwrócić uwagę na: Otoczenie: jak wygląda dom tej osoby? Czy jest schludny, czy panuje w nim bałagan? Duży dom czy małe mieszkanie? Co robi ta osoba po powrocie? Zmienia ubranie, bierze prysznic, a może najpierw pije piwo? Co je? Obiad z mikrofalówki, na wynos, pizzę z dostawą czy płatki kukurydziane? W jakim jest nastroju? Jak minął jej dzień w pracy? Wariacje: Możecie wymyślić inne sytuacje, w których postacie wchodzą do danej lokalizacji."
        },
        44: {
            "opis_ang": "This is like Ding: players play a scene. When a bell rings, they both need to snap into a completely different character, but the scene continues. This exercise is not likely to lead to good scenes, but it is a great help in teaching players to snap into distinct and varied characters in a flash.",
            "opis": "To jest jak Ding: gracze odgrywają scenkę. Kiedy dzwoni dzwonek, obaj muszą natychmiast wcielić się w zupełnie inną postać, ale scena toczy się dalej. To ćwiczenie raczej nie doprowadzi do dobrych scen, ale jest świetną pomocą w nauczeniu graczy błyskawicznego tworzenia wyraźnych i zróżnicowanych postaci."
        },
        45: {
            "opis_ang": "This is a Long Form format that can be played with a large number of players. The audience suggests a kind of disaster (flood, earthquake, alien invasion, you name it) and a location where the play will unfold, preferably a place where lots of characters can be found. Examples are a tropical paradise for tourists, a large building. The story starts just before the disaster, usually some character foreseeing the disaster, by discovering a bad omen or some predicting sign. Then we see a multitude of characters at the location. These should be archetypical characters one would find in typical disaster movies. Examples are: an old couple that have been together forever (will die); a priest that can lead the survivors (will die); a mad scientist that will have a miraculous solution to escape the disaster (will die); a fallen hero, ex-cop thrown of the force, retired fireman, ex-lifeguard with a coke addiction, you get the picture (will rise to the occasion and survive); a kid with loving parents (or a troublesome teenager not getting along with parents) (kid will survive, parents will die); some troubled, dysfunctional character set up to become the hero's love interest. Watch a couple of disaster movies and pick your favorite cliché characters. Then, the disaster strikes. Light, sound and smoke effects are a must. Why not use a musician with an electric guitar doing distortion for color. The next scenes show the characters in their quest for survival. Most of them will die (in a spectacular way). Feel free to feature character backgrounds by means of flashbacks. The story ends with the hero + love interest + kid (if available and/or still alive) escaping the massacre, ready and set to live happily ever after.",
            "opis": "To format długiej formy, który można grać z dużą liczbą graczy. Publiczność sugeruje rodzaj katastrofy (powódź, trzęsienie ziemi, inwazja kosmitów) i lokalizację, w której rozegra się akcja – najlepiej miejsce, gdzie można spotkać wiele różnych postaci, np. tropikalny kurort lub duży budynek. Historia zaczyna się tuż przed katastrofą, często jakaś postać ją przewiduje, odkrywając zły omen. Następnie poznajemy wiele archetypowych postaci, typowych dla filmów katastroficznych, np. stara para (zginie), ksiądz-bohater (zginie), szalony naukowiec (zginie), upadły bohater (przeżyje), dziecko z rodzicami (dziecko przeżyje, rodzice zginą), przyszła sympatia bohatera. Obejrzyjcie kilka filmów katastroficznych i wybierzcie ulubione klisze. Następnie uderza katastrofa (efekty świetlne i dźwiękowe mile widziane). Kolejne sceny pokazują walkę o przetrwanie, w której większość postaci ginie w spektakularny sposób. Można używać retrospekcji. Historia kończy się ucieczką bohatera, jego sympatii i dziecka (jeśli przeżyło), gotowych na szczęśliwe życie."
        },
        46: {
            "opis_ang": "This is a Long Form that starts with a number of monologues, each based on a character built from a picture of a face, projected on stage. Prepare a series of pictures of faces, make sure the players don't get to see them before the performance. Pick 3-5 players and randomly assign a face to each. The audience provides input on the faces, e.g. the character's name, motivations, desires, social background, etc. The player then presents his character in a monologue, based on the picture as well as on the audience suggestions. Once all main characters have been introduced in monologues, a series of scenes is played, in which the introduced characters play the lead. Players that play a 'face' character do not play other characters, but supporting players can play side characters (and can play more than one character).",
            "opis": "To długa forma, która zaczyna się od serii monologów. Każdy monolog oparty jest na postaci stworzonej na podstawie zdjęcia twarzy, wyświetlonego na scenie. Przygotujcie serię zdjęć twarzy (nie pokazujcie ich graczom wcześniej). Wybierzcie 3-5 graczy i losowo przypiszcie każdemu twarz. Publiczność podaje informacje o postaciach (imię, motywacje, pragnienia). Gracze przedstawiają swoje postacie w monologach. Po monologach następuje seria scenek z udziałem wprowadzonych postaci. Gracze „twarzowi” grają tylko swoje postacie, ale inni mogą grać postacie poboczne."
        },
        47: {
            "opis_ang": "Fun game that will force everyone to cooperate. Players will 'build' family portraits. Ask for e.g. a family of accountants, of bean counters, of fat/thin people, of pop stars, of snakes, rats, cats, garden tools. Tell the players you will want to see who is who in the family. We also want to see who gets along with whom, who's the black sheep of the family, and so on. This only works if players watch each other carefully.",
            "opis": "Zabawna gra, która zmusza wszystkich do współpracy. Gracze będą „budować” portrety rodzinne. Poproście o sugestię, np. rodzina księgowych, grubasów, gwiazd popu, węży, szczurów, kotów, narzędzi ogrodowych. Celem jest pokazanie, kto jest kim w rodzinie, kto się z kim dogaduje, a kto jest czarną owcą. To działa tylko wtedy, gdy gracze uważnie się obserwują."
        },
        48: {
            "opis_ang": "Laban was a movement theoretician, and this exercise is based on (a simplified form of some of) his ideas. Take 3 categories: Timing: Sudden or Sustained; Weight: Heavy or Light; Space: Direct or Indirect. Then try and create characters that behave/talk according to combinations of these 3 categories: punching: sudden / heavy / direct; slashing: sudden / heavy / indirect; wringing: sustained / heavy / indirect; gliding: sustained / light / indirect; dabbing: sudden / light / direct; smoothing: sustained / light / direct; pressing: sustained / heavy / direct. Notes: The attributes go with the characters, not necessarily with the actual body of the performer. A heavily built person can move lightly. Variations: You can introduce this in a fairly simple way, by asking players to move about the room, according to directions or orientations: be a 'horizontal' or a 'vertical' person; be down, or up; be light, or heavy. Then experiment with this: be suddenly light (a bird taking off from a tree) or sustainedly light (be a cloud). You can do this using different kinds of music. What direction / weight / movement does a particular song or theme inspire? Then try and experiment with characters: what or who would a vertical person be (a general?). What/who would a sustainedly light person be (stoned?). Suddenly light (flirty?). See also Fast Food Stanislavski. Origin: Attributed to Keith Johnstone. See 'Impro for Storytellers'.",
            "opis": "Laban był teoretykiem ruchu, a to ćwiczenie opiera się na uproszczonej formie jego pomysłów. Przyjmijcie 3 kategorie: Czas (Nagły/Trwały), Waga (Ciężki/Lekki), Przestrzeń (Bezpośrednia/Pośrednia). Twórzcie postacie, które zachowują się i mówią zgodnie z kombinacjami tych kategorii (np. pchnięcie: nagłe/ciężkie/bezpośrednie). Uwagi: Atrybuty dotyczą postaci, a nie ciała aktora. Ciężka osoba może poruszać się lekko. Wariacje: Zacznijcie prosto, prosząc graczy o poruszanie się w określony sposób (np. „bądź osobą poziomą”, „bądź lekki”). Eksperymentujcie z postaciami: kim byłaby osoba „pionowa” (generał?), a kim „stale lekka” (naćpana?). Zobacz też Fast Food Stanisławskiego. Pochodzenie: Keith Johnstone."
        },
        49: {
            "opis_ang": "Ask 2 players to play a scene, perhaps give them a title or a location, but also give them a subtext for their character. Subtexts can be: you want to seduce the other person; you are a nerd; you like to make people laugh; you want to impress others; you are a nasty person; you try to be ordinary; you are an optimist/pessimist; you'll never find a girlfriend/boyfriend. Notes: If you use this in a workshop, it may be a good idea to ask the players how someone would behave given a particular subtext. Emphasize that you are looking for Truth. This is an excellent technique to find a character. You can actually use this for performance - just give yourself a subtext when you jump on stage and see what happens. See also Status. Origin: Described in 'Impro for Storytellers': the book has an appendix on how to play for different subtexts.",
            "opis": "Poproście dwóch graczy o odegranie scenki, dając im tytuł lub lokalizację oraz podtekst dla ich postaci. Podteksty mogą być różne, np. „chcesz uwieść drugą osobę”, „jesteś kujonem”, „chcesz zaimponować innym”. Uwagi: Na warsztatach zapytajcie graczy, jak ktoś zachowałby się z danym podtekstem. Podkreślajcie, że szukacie prawdy. To doskonała technika do budowania postaci. Można jej używać na występach – po prostu dajcie sobie podtekst i zobaczcie, co się stanie. Zobacz również Status. Pochodzenie: Opisane w „Impro for Storytellers” Keitha Johnstone’a."
        },
        50: {
            "opis_ang": "Silly physical warm-up. Have everybody mill around the room, and shout a body part. Players then start moving around as if they are led by that body part. Continue with another body part. End the game on a really silly note by leading with, e.g., your internal organs. Also known as Foot Soldiers.",
            "opis": "Zabawna rozgrzewka fizyczna. Niech wszyscy kręcą się po pokoju, a Ty wykrzyknij nazwę części ciała. Gracze zaczynają się poruszać, jakby kierowała nimi ta część ciała. Kontynuuj z inną częścią ciała. Zakończ grę w naprawdę głupi sposób, prowadząc ją np. swoimi organami wewnętrznymi. Znane również jako Żołnierze Piechoty."
        },
        51: {
            "opis_ang": "Open a fortune cookie, read it aloud. Then improvise a scene based on the fortune. Variations: Give every player a fortune cookie; each player then needs to show that fortune in his or her character.",
            "opis": "Otwórz ciasteczko z wróżbą i przeczytaj ją na głos. Następnie zaimprowizuj scenę opartą na wróżbie. Wariacje: Daj każdemu graczowi ciasteczko z wróżbą; każdy gracz musi następnie przedstawić tę wróżbę w swojej postaci."
        },
        52: {
            "opis_ang": "All players start milling about the room. You then ask them to greet each other, perhaps just by shaking hands. Players just shake hands, move on, and greet the next player they meet. Then ask the players to greet each other in a more specific way. Possibilities are: greet each other like you greet a long lost friend; greet someone you don't really trust; greet an ex-lover; greet someone you really hate; someone you have a secret crush on; someone you had a one-night stand with; someone that sold you a crappy used car; someone with bad breath; greet someone like you are a cowboy, a soldier, a nanny, a Russian farmer... Also known as Hello. Also known as Lost Friend. See also Presents.",
            "opis": "Wszyscy gracze zaczynają krążyć po pokoju. Następnie poproś ich, aby się przywitali, być może po prostu podając sobie dłonie. Gracze podają sobie ręce, idą dalej i witają kolejnego napotkanego gracza. Następnie poproś graczy, aby przywitali się w bardziej konkretny sposób. Możliwości to: przywitaj się jak z dawno niewidzianym przyjacielem; przywitaj kogoś, komu nie do końca ufasz; przywitaj byłą miłość; przywitaj kogoś, kogo nienawidzisz; kogoś, w kim się skrycie podkochujesz; kogoś, z kim miałeś jednonocną przygodę; kogoś, kto sprzedał ci kiepski używany samochód; kogoś z nieświeżym oddechem; przywitaj się jak kowboj, żołnierz, niania, rosyjski rolnik... Znane również jako Cześć. Znane również jako Zaginiony Przyjaciel. Zobacz także Prezenty."
        },
        53: {
            "opis_ang": "Very silly, but very effective. Ask the audience for a fairy tale. Then give each player one or more characters from that story. Ask for a handicap or a peculiar state of mind for each character and improvise the fairy tale.",
            "opis": "Bardzo głupia, ale skuteczna gra. Poproście publiczność o bajkę. Dajcie każdemu graczowi jedną lub więcej postaci z tej historii. Poproście o ułomność lub dziwny stan umysłu dla każdej postaci i zaimprowizujcie bajkę."
        },
        54: {
            "opis_ang": "Ask for suggestions for an attitude, e.g. \"Nobody loves me\" or \"I never met a man I didn't like\". Then go through a series of life events that show that attitude (graduation, office party, retirement home, etc.). See also Character Gauntlet.",
            "opis": "Poproście o sugestie dotyczące postawy, np. „Nikt mnie nie kocha” lub „Nigdy nie spotkałem człowieka, którego bym nie lubił”. Następnie przejdźcie przez serię wydarzeń z życia, które ilustrują tę postawę (ukończenie studiów, impreza w biurze, dom starców itp.). Zobacz także Rękawica Postaci."
        },
        55: {
            "opis_ang": "This is a character exercise. 2 players will play a scene in a shop. The quality of the scene does not really matter here; just enter the shop, order what you need, pay for it and leave. Give us an item (a carrot), and we have a scene in a carrot shop. One player is designated as the shop owner, and the other will play a customer. The idea is to give the 'customer' a basis to build a character. She enters the shop in that character, and the other player (the shopkeeper) tries to imitate that character as closely as possible. Use the tricks below as a basis for building a character: Ask the 'customer' to talk to you in different voices. Pick one, and there you go. Ask the 'customer' to make different kinds of faces. Pick one, and there you go. Pick a body part (the elbow). Pick one body part (the elbow). Pick an emotion and there you go. Ask her to move a bit, dance, and have her freeze. The position she's frozen in is her inspiration for the customer character. This is an exercise for both players, but what is being exercised is different for both: for the customer the exercise is to build a character out of a silly suggestion. Note that there are no good and bad characters; anything in the position/suggestion given to the player can be used as an inspiration, even if the 'link' between the suggestion and the actual character is not obvious. The only goal is to come up with interesting, strong characters. For the shopkeeper it is a listening/observation exercise. The idea is not for the shopkeeper to build a character out of the suggestion, but to imitate the character traits of the customer as closely as possible. See also Opposite Characters.",
            "opis": "To ćwiczenie na budowanie postaci. Dwóch graczy odgrywa scenkę w sklepie. Jakość sceny nie ma znaczenia. Dajcie im przedmiot (np. marchewkę), a będzie to sklep z marchewkami. Jeden gracz jest właścicielem, drugi klientem. Klient otrzymuje podstawę do zbudowania postaci (np. przez śmieszny głos, minę, ruch), a właściciel sklepu stara się jak najwierniej naśladować tę postać. Celem klienta jest stworzenie ciekawej, silnej postaci. Celem sklepikarza jest ćwiczenie słuchania i obserwacji. Zobacz także Postacie Przeciwne."
        },
        56: {
            "opis_ang": "This is at various times a physical warm-up, a physical association game, or a game for character work. The game is played individually, but all players can do this simultaneously. All players mill about the room. At any point the trainer yells \"Yes!\", at which point all players 'jump' into a position. Trainer can (but does not have to) sidecoach by shouting 'direction' (see Fast Food Laban ) like 'horizontal', 'up', 'down', 'sideways', 'big', 'small', 'light', 'heavy'. The idea then is to let the position into one has jumped inspire the player to a character, a situation. The inspiration comes from associating the position with, erm, well, whatever comes to mind. See also Association Jump for an extension of this exercise.",
            "opis": "To ćwiczenie może być rozgrzewką fizyczną, grą w skojarzenia fizyczne lub grą na pracę z postacią. Gra jest indywidualna, ale wszyscy gracze mogą ją wykonywać jednocześnie. Wszyscy gracze krążą po pokoju. W dowolnym momencie trener krzyczy „Tak!”, a wtedy wszyscy gracze „wskakują” w określoną pozycję. Trener może (ale nie musi) podpowiadać, krzycząc „kierunek” (patrz Fast Food Laban), np. „poziomo”, „w górę”, „w dół”, „na boki”, „duży”, „mały”, „lekki”, „ciężki”. Celem jest, aby pozycja, w którą wskoczył gracz, zainspirowała go do stworzenia postaci lub sytuacji. Inspiracja pochodzi ze skojarzenia pozycji z... cóż, z czymkolwiek, co przyjdzie do głowy. Zobacz także Skok Skojarzeniowy, aby poznać rozszerzenie tego ćwiczenia."
        },
        57: {
            "opis_ang": "Everyone in a circle and picks an animal, a motion and a noise for that animal. One person \"sends\" the action to another person by making their own noise/motion, and then someone else's noise/motion. That person, in turn, makes their noise/motion, and then another person's. Cat, monkey, and dog are commonly used, but creativity is encouraged...the sillier, the better! If someone \"messes up\", they're out for that round. Last person still in is the winner.",
            "opis": "Wszyscy w kręgu wybierają zwierzę, ruch i dźwięk dla tego zwierzęcia. Jedna osoba „wysyła” akcję do innej osoby, wykonując swój własny dźwięk/ruch, a następnie dźwięk/ruch kogoś innego. Ta osoba z kolei wykonuje swój dźwięk/ruch, a potem kolejnej osoby. Kot, małpa i pies są powszechnie używane, ale kreatywność jest mile widziana... im głupiej, tym lepiej! Jeśli ktoś się pomyli, odpada z tej rundy. Ostatnia osoba w grze wygrywa."
        },
        58: {
            "opis_ang": "This is another Long Form improv format. The name comes from a movie, which in turn is based on a novel by Arthur Schnitzler, called Traumnovelle, in which a series of characters go to bed with each other in sequence, from the first to the last, and back to the first. The format is quite simple: we play scenes, in which with every switch of scene the 'oldest' character disappears, and a new scene is played with the remaining character, and a new one. The form ends when the circle closes, and the last and the first character do a scene. Obviously there is no need for all characters to sleep with each other! Scene switching is done by tagging (as in Freeze Tag). The idea is to see different aspects of a character, in different situations, interacting with different characters. See also Status Chain.",
            "opis": "To kolejny format długiej formy improwizacji. Nazwa pochodzi od filmu, który z kolei oparty jest na powieści Arthura Schnitzlera „Traumnovelle”, w której seria postaci kolejno idzie ze sobą do łóżka, od pierwszej do ostatniej i z powrotem do pierwszej. Format jest prosty: gramy sceny, w których przy każdej zmianie sceny znika „najstarsza” postać, a nowa scena jest odgrywana z pozostałą postacią i nową. Forma kończy się, gdy koło się zamyka, a ostatnia i pierwsza postać grają scenę. Oczywiście nie ma potrzeby, aby wszystkie postacie spały ze sobą! Zmiana sceny odbywa się przez oznaczenie (jak w Freeze Tag). Chodzi o to, by zobaczyć różne aspekty postaci w różnych sytuacjach, wchodzących w interakcje z różnymi postaciami. Zobacz także Łańcuch Statusu."
        },
        59: {
            "opis_ang": "Let the players play a short scene. Then ask them to repeat the following mantra in their head and replay the scene: 'I'm so happy, I'm so happy'. In many cases, you will find that the whole scene becomes happier. Variations: Try with other mantras, like 'I hate you', and see what the effect is. Let players choose a mantra, and then play a scene. See Mantra Introduction for more about mantras. See also \"Impro for Storytellers\" for a discussion on the use of Mantras. (Compare to Fast Food Stanislawski.)",
            "opis": "Pozwólcie graczom odegrać krótką scenę. Następnie poproście ich, aby powtórzyli w myślach następującą mantrę i odegrali scenę ponownie: „Jestem taki szczęśliwy, jestem taki szczęśliwy”. W wielu przypadkach zauważycie, że cała scena staje się szczęśliwsza. Wariacje: Spróbujcie z innymi mantrami, jak „Nienawidzę cię”, i zobaczcie, jaki będzie efekt. Pozwólcie graczom wybrać mantrę, a następnie odegrajcie scenę. Więcej o mantrach znajdziecie we Wprowadzeniu do Mantr. Zobaczcie też „Impro dla Opowiadaczy” w celu dyskusji na temat użycia mantr. (Porównajcie z Fast Food Stanisławski)."
        },
        60: {
            "opis_ang": "Players in a scene call for new characters, by giving them names that refer to character or physical traits. Things like: Ah, here comes Mr. Bad Irish Accent; I think we need Mrs. Pathological Liar for this one; Dear dear, if that isn't Sir Eats-People. And so on. The idea is to challenge the other players with weird and unexpected suggestions, and forcing them to come up with an extravagant character right away. In a sense this is really institutionalized Pimping. Another game in which similar pimping is used would be Supermen.",
            "opis": "Gracze w scenie wołają o nowe postacie, nadając im imiona nawiązujące do charakteru lub cech fizycznych. Na przykład: „Ach, nadchodzi Pan Zły Irlandzki Akcent”; „Chyba potrzebujemy do tego Pani Patologicznej Kłamczuchy”; „O rety, czy to nie Sir Zjada-Ludzi”. I tak dalej. Celem jest rzucenie wyzwania innym graczom dziwnymi i nieoczekiwanymi sugestiami, zmuszając ich do natychmiastowego wymyślenia ekstrawaganckiej postaci. W pewnym sensie jest to zinstytucjonalizowane nagabywanie. Inną grą, w której używa się podobnego nagabywania, jest Supermen."
        },
        61: {
            "opis": "Zbierzcie czyjeś inicjały, a następnie, jako grupa, wymyślcie tytuły filmów na podstawie tych inicjałów. Wybierzcie jeden tytuł i odegrajcie scenę początkową z tego filmu."
        },
        62: {
            "opis": "Zbierzcie sugestie dotyczące problemu w małym miasteczku, a następnie członkowie rady pytają mieszkańców, co sądzą o tym problemie."
        },
        63: {
            "opis_ang": "Improvise a scene with 2 players, and give them a job (or let the audience provide the job). Then tell them what job they had in a previous life. The idea is that somehow in the scene characters reflect their previous jobs in their actual life. The idea is not to 'play' the old job, but to show character traits of someone with the old job while performing the new job.",
            "opis": "Zaimprowizujcie scenę z dwoma graczami i dajcie im pracę (lub pozwólcie publiczności ją zasugerować). Następnie powiedzcie im, jaką pracę wykonywali w poprzednim życiu. Chodzi o to, aby postacie w scenie w jakiś sposób odzwierciedlały swoje poprzednie zawody w obecnym życiu. Celem nie jest „odgrywanie” starej pracy, ale pokazywanie cech charakteru osoby z poprzedniej pracy podczas wykonywania nowej."
        },
        64: {
            "opis_ang": "This is basically the opposite of Imitate: for the shopkeeper, instead of imitating the character of the customer, try and build a complete opposite character. As side-coaching, point players to the following character traits: Voice (loud/soft/sharp ? intonation?) - Status (high/low?) - Age? Profession? Way of moving the body? (have a look at Fast Food Laban for more on movement). Note that this is also a looking/listening exercise for the shopkeeper!",
            "opis": "To w zasadzie przeciwieństwo gry „Naśladuj”: sklepikarz, zamiast naśladować postać klienta, stara się zbudować postać całkowicie przeciwną. Jako wskazówkę, zwróćcie uwagę graczy na następujące cechy charakteru: Głos (głośny/cichy/ostry? intonacja?), Status (wysoki/niski?), Wiek? Zawód? Sposób poruszania się? (zajrzyjcie do Fast Food Laban, aby dowiedzieć się więcej o ruchu). Zauważcie, że jest to również ćwiczenie na patrzenie/słuchanie dla sklepikarza!"
        },
        65: {
            "opis_ang": "Let the players walk around the room in silence. Ask them how they would classify themselves: high or low status; loud or quiet; caring or sloppy; strong or weak; tall or small; secure or insecure; clumsy or graceful; happy or sad; introvert or extrovert; basically anything that would be a trait. Then ask them to imagine they are the exact opposite of all these character traits. Have them move like such a character. Then play scenes in which players 'become' the opposites of their own characters.",
            "opis": "Pozwólcie graczom spacerować po pokoju w ciszy. Zapytajcie ich, jak by siebie sklasyfikowali: wysoki czy niski status; głośny czy cichy; opiekuńczy czy niechlujny; silny czy słaby; wysoki czy niski; pewny siebie czy niepewny; niezdarny czy zgrabny; szczęśliwy czy smutny; introwertyk czy ekstrawertyk – w zasadzie każda cecha. Następnie poproście ich, aby wyobrazili sobie, że są dokładnym przeciwieństwem wszystkich tych cech. Niech poruszają się jak taka postać. Potem odegrajcie sceny, w których gracze „stają się” przeciwieństwami samych siebie."
        },
        66: {
            "opis_ang": "Everyone in a circle. The coach starts by passing a famous person's name across the circle. The player that he points to should respond (in character) with something the famous person might say (just fake it if you don't know who that person is). Afterwards, everyone shouts: \"That was awesome!\" E.g. \"William Shakespeare\" - \"To be or not to be.. 'tis still the question, after innumerable eons of time\" (with Old English accent) - \"That was awesome!\" See also Family Portraits.",
            "opis": "Wszyscy w kręgu. Trener zaczyna, podając imię znanej osoby przez krąg. Gracz, na którego wskaże, powinien odpowiedzieć (w postaci) czymś, co ta znana osoba mogłaby powiedzieć (po prostu udawaj, jeśli nie wiesz, kim jest). Następnie wszyscy krzyczą: „To było niesamowite!”. Np. „William Shakespeare” – „Być albo nie być... to wciąż pytanie, po niezliczonych eonach czasu” (ze staroangielskim akcentem) – „To było niesamowite!”. Zobacz także Portrety Rodzinne."
        },
        67: {
            "opis": "Gracz A przypomina sobie prawdziwą osobę ze swojego życia (lub wyobraża sobie kogoś) i odnosi się do gracza B jak do tej osoby."
        },
        68: {
            "opis": "3 sceny: środek związku, początek i przyszłość. Unikajcie rozstań, pokażcie, jak rozwijają się pewne typy związków. (Pokażcie „dlaczego” związku, które wyrasta z „dlaczego” poszczególnych postaci)."
        },
        69: {
            "opis_ang": "The scene takes place in two rooms. One room is on the left half of the stage, the other room is on the right half of the stage. Two players are in each half. Two of the four stand off-stage. The players on stage are two different characters, the players off-stage will both play the same character. One of the off-stage characters will enter their room and start a scene based on the suggestion. He or she will have to go into the other room. When the character exits the room, the off-stage player on the other side enters and continues the scene, switching back and forth.",
            "opis": "Scena rozgrywa się w dwóch pokojach. Jeden pokój znajduje się po lewej stronie sceny, a drugi po prawej. W każdej połowie jest dwóch graczy. Dwóch z czterech stoi poza sceną. Gracze na scenie to dwie różne postacie, a gracze poza sceną będą grać tę samą postać. Jedna z postaci spoza sceny wejdzie do swojego pokoju i rozpocznie scenę na podstawie sugestii. Będzie musiała przejść do drugiego pokoju. Kiedy postać opuści pokój, gracz spoza sceny po drugiej stronie wejdzie i będzie kontynuował scenę, zmieniając się w tę i z powrotem."
        },
        70: {
            "opis_ang": "Have everyone walk around leisurely. Tell them to stop and start making a movement, a gesture, a sound, anything really. Let the players repeat the gesture until they know what they 'are'. The idea is not to preconceive, but to let it happen. Players may turn out to be dishwashers, ushers, lawn mowers, ping pong balls, whatever. Explain that there are no wrong answers. Tell the players just to acknowledge what they 'are' for themselves, and then move on, stop again and make another gesture/movement/sound.",
            "opis": "Niech wszyscy swobodnie spacerują. Powiedzcie im, żeby się zatrzymali i zaczęli wykonywać jakiś ruch, gest, dźwięk – cokolwiek. Niech gracze powtarzają ten gest, aż dowiedzą się, kim „są”. Chodzi o to, żeby nie planować z góry, ale pozwolić, by to się stało. Gracze mogą okazać się zmywarkami, bileterami, kosiarkami, piłeczkami pingpongowymi, czymkolwiek. Wyjaśnijcie, że nie ma złych odpowiedzi. Powiedzcie graczom, żeby po prostu uznali dla siebie, kim „są”, a potem ruszyli dalej, zatrzymali się i wykonali kolejny gest/ruch/dźwięk."
        },
        71: {
            "opis": "Konkretne jednowyrazowe sugestie dla wszystkich graczy (np. „narzędzie domowe”, „typ samochodu” itp.), a następnie łańcuch krótkich dwuosobowych wywiadów, każdy oparty na jednej sugestii."
        },
        72: {
            "opis_ang": "This is a group exercise for building Characters. One player on a chair, up to 5 other players sit in front of her. The player on the chair starts by taking something out of a large mime bag. She holds the object in front of her and names it - anything that comes to mind is just fine (see Warehouse, Open Your Hand or Presents). The other players start asking the middle player questions about the object, why she has it, what it might mean to her. After a couple of questions, the middle player is asked to take another object out of the bag - again this can be anything and it need not be related to the first object that popped up. This triggers more questions and more objects. Continue until we get to know the character that sits on the chair. Notes: The idea of the exercise is to construct a character as a group. Both the objects and the questions and the answers to them will provide clues as to who the person on the chair might be. Avoid very directive questions, although any element in the questions should probably be accepted. As soon as the person on the chair has an idea about who she might be, what her state of mind might be, what her age might be, what her status might be, she should start showing these traits, until she really 'becomes' the character. Use voice and body language to express this.",
            "opis": "To grupowe ćwiczenie na budowanie postaci. Jeden gracz siedzi na krześle, a przed nim grupa do 5 graczy. Gracz na krześle wyjmuje z wyimaginowanej torby przedmiot i go nazywa. Pozostali gracze zadają mu pytania dotyczące tego przedmiotu. Po kilku pytaniach gracz wyjmuje kolejny przedmiot, co prowokuje kolejne pytania. Kontynuujcie, aż poznamy postać siedzącą na krześle. Celem jest wspólne skonstruowanie postaci. Zarówno przedmioty, jak i pytania i odpowiedzi dostarczają wskazówek. Unikajcie pytań naprowadzających. Gdy osoba na krześle wczuje się w postać, powinna zacząć ją odgrywać."
        },
        73: {
            "opis": "Zapytajcie publiczność, jak jesteście ubrani, co macie przy sobie itp., a następnie odegrajcie scenę w oparciu o tę wiedzę."
        },
        74: {
            "opis_ang": "This is a 2-player scene in which the lines are scripted. Here's the script: (1) {Knocks on door} (2) Come in. You know why I called you in? (1) {Says she doesn't know why} (2) {Hands 1 a (mimed) slip of paper} (1) I thought you would not hold that against me? (2) You're fired. (1) That's fine. I hated this stupid job anyway. Ask the players to play this scene. They need to stick to the script, but they can really do anything, as long as they don't add any lines. It probably won't be all that interesting. Then have them replay the scene, but give them side-coaching (which the other player and the audience or the rest of the group do not hear). See if the scenes get more interesting. Things you can give to a player can be: You are nervous, happy, sad, you are afraid of the other. The other smells nice/stinks. You had beans/garlic. You are turning into a crow/monkey/cow. You are in a wheelchair. You are trying to pick up the other person. Your underwear does not quite fit (it's too small). You are a bit deaf, can't find your glasses, lost a contact, lost your dentures. You are a kleptomaniac. Notes: Players can do quite a lot without deviating from the script. They can build/open doors, windows, cabinets, make all kinds of noises or faces. Remind players they can vary status. Perhaps, they could try and clarify what is on the note? Is it something bad, or petty, or funny, or sad? Variations: Feel free to invent another scene, with other lines. (Or do a replay of a simple improvised scene, even a 3-line one, they could try in layups). See also Fast Food Stanislavski. See Scene Replay.",
            "opis": "To scena dla dwóch graczy ze scenariuszem. Scenariusz: (1) {Puka do drzwi} (2) Wejdź. Wiesz, dlaczego cię wezwałem? (1) {Mówi, że nie wie} (2) {Wręcza kartkę} (1) Myślałem, że nie weźmiesz tego pod uwagę? (2) Jesteś zwolniony. (1) W porządku. I tak nienawidziłem tej głupiej pracy. Gracze muszą trzymać się scenariusza, ale mogą swobodnie interpretować swoje działania. Następnie powtarzają scenę, ale z tajnymi wskazówkami od trenera (np. „jesteś zdenerwowany”, „próbujesz poderwać drugą osobę”). Gracze mogą wiele zrobić, nie odbiegając od scenariusza, np. zmieniać status, budować otoczenie, wydawać dźwięki. Zobacz też Fast Food Stanisławski i Powtórka Sceny."
        },
        130: {
            "opis_ang": "An improvised scene is played, which any of the players can interrupt at any time by yelling 'freeze'. At that point the player steps out of the scene and tells the audience what his character is really thinking, after which the scene is continued. The other characters are of course not supposed to know what the players are thinking, but the players are, and should use this. Notes: Players can use this to reveal their hidden motives. The other players can play into this, or deliberately ignore this knowledge. Gimmick: characters may in fact have other things on their mind than what is going on in the particular scene. E.g. a driver pulled over by a cop might be thinking about the groceries his wife told him to get at the supermarket. See also Commenting. See also Scene Painting for another game that uses a similar technique. Variations: The players' thoughts can also be provided by players off-scene (angels/devils), who can use the players' body and vocal clues to reveal their hidden emotions. Also known as Alter Ego. Also known as Consciences.",
            "opis": "Odgrywana jest improwizowana scena, którą każdy z graczy może w każdej chwili przerwać, krzycząc „freeze”. W tym momencie gracz wychodzi ze sceny i mówi publiczności, co jego postać naprawdę myśli, po czym scena jest kontynuowana. Pozostałe postacie oczywiście nie mają wiedzieć, co myślą gracze, ale gracze wiedzą i powinni to wykorzystać. Uwagi: Gracze mogą wykorzystać to do ujawnienia swoich ukrytych motywów. Inni gracze mogą w to grać lub celowo ignorować tę wiedzę. Sztuczka: postacie mogą mieć w rzeczywistości inne rzeczy na głowie niż to, co dzieje się w danej scenie. Np. kierowca zatrzymany przez policjanta może myśleć o zakupach spożywczych, które żona kazała mu kupić. Zobacz także: Komentowanie, Malowanie Sceny. Wariacje: Myśli graczy mogą być również dostarczane przez graczy spoza sceny (anioły/diabły), którzy mogą używać wskazówek ciała i głosu graczy, aby ujawnić ich ukryte emocje. Znane również jako Alter Ego lub Sumienia."
        }
    }

    # This is just a sample. I will now generate the translations for the rest of the file.
    # The following dictionary will be much larger in the actual execution.

    # Let's assume I have the full dictionary of translations now.
    # I will create a script that applies all of them.

    for game in data:
        game_id = game.get('nr_katalogowy')
        if game_id in translations:
            translation_data = translations[game_id]
            if 'opis' in translation_data:
                game['opis'] = translation_data['opis']
            if 'opis_ang' in translation_data:
                game['opis_ang'] = translation_data['opis_ang']

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

if __name__ == '__main__':
    apply_translations()
